/**
 * GENERATED by scripts/bundle-migrations.mjs — do not edit.
 *
 * The SQL below is inlined so the deployment carries its own migrations (see
 * the script's header for why runtime file reads are not reliable on Vercel).
 * Regenerate with: node scripts/bundle-migrations.mjs
 */

export interface BundledMigration {
  name: string;
  sql: string;
}

export const MIGRATIONS: BundledMigration[] = [
  {
    name: "00000000000001_init_marketing_os.sql",
    sql: `-- Users table (extends auth.users)
CREATE TABLE IF NOT EXISTS public.users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  role TEXT DEFAULT 'member',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Skills execution log
CREATE TABLE IF NOT EXISTS public.skill_executions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  skill_id TEXT NOT NULL,
  user_id UUID REFERENCES public.users(id),
  status TEXT NOT NULL,
  input JSONB,
  output JSONB,
  error TEXT,
  started_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

-- Agent conversations
CREATE TABLE IF NOT EXISTS public.conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.users(id),
  title TEXT,
  messages JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Integration credentials (encrypted)
CREATE TABLE IF NOT EXISTS public.integrations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type TEXT NOT NULL,
  credentials JSONB NOT NULL,
  enabled BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.skill_executions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.integrations ENABLE ROW LEVEL SECURITY;

-- RLS Policies
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can view own data' AND tablename = 'users') THEN
    CREATE POLICY "Users can view own data" ON public.users FOR SELECT USING (auth.uid() = id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can update own data' AND tablename = 'users') THEN
    CREATE POLICY "Users can update own data" ON public.users FOR UPDATE USING (auth.uid() = id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can view own skills' AND tablename = 'skill_executions') THEN
    CREATE POLICY "Users can view own skills" ON public.skill_executions FOR SELECT USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can view own conversations' AND tablename = 'conversations') THEN
    CREATE POLICY "Users can view own conversations" ON public.conversations FOR SELECT USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Admins can manage integrations' AND tablename = 'integrations') THEN
    CREATE POLICY "Admins can manage integrations" ON public.integrations FOR ALL USING (
      EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
    );
  END IF;
END $$;
`,
  },
  {
    name: "00000000000002_user_signup_trigger.sql",
    sql: `-- Trigger function to create public.users record on auth signup
-- First user becomes admin, subsequent users are members
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  user_count INTEGER;
  user_role TEXT;
BEGIN
  -- Count existing users to determine role
  SELECT COUNT(*) INTO user_count FROM public.users;

  -- First user becomes admin, others are members
  IF user_count = 0 THEN
    user_role := 'admin';
  ELSE
    user_role := 'member';
  END IF;

  -- Insert the new user record
  INSERT INTO public.users (id, email, role, created_at, updated_at)
  VALUES (
    NEW.id,
    NEW.email,
    user_role,
    NOW(),
    NOW()
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger on auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- Grant necessary permissions
GRANT USAGE ON SCHEMA public TO supabase_auth_admin;
GRANT ALL ON public.users TO supabase_auth_admin;
`,
  },
  {
    name: "008_email_review_notes.sql",
    sql: `-- =============================================================================
-- 008 — Review notes on email campaigns (spec 25 — the hosted review loop)
-- =============================================================================
-- A shared review link (HMAC, 30-day expiry) opens the review room: the
-- assembled email plus the context needed to judge it. Reviewers leave notes
-- there; the agent reads them back in-session and revises. This is the table
-- behind that loop.
--
-- IDENTITY WARNING — read before building anything on top of \`author\`:
--   These notes arrive through a TOKEN-GATED PUBLIC surface. A valid token
--   proves possession of a link, not identity, and \`author\` is whatever the
--   reviewer typed into a text box. It is a courtesy label for a conversation,
--   NOT an authenticated actor.
--   Never treat a note as an approval, an authorisation, or an audit record.
--   Approval keeps its own path: Slack, real user id, mos_action_audit.
--   \`source\` exists to keep that distinction legible forever — a future
--   console-authenticated note lane can write 'console' and be trusted more,
--   without silently upgrading the trust of every 'link' row already here.
--
-- Doctrine (spec 22 D1): files are truth, DB is the index. Notes are the
-- exception and are honestly DB-native — they are conversation ABOUT the
-- artifact, not the artifact. Losing them loses discussion, not campaigns.
--
-- Governance mirrors 003/004/007: RLS on, authenticated + anon denied, the
-- app writes as owner through the pooled connection. No secrets.
-- =============================================================================

CREATE TABLE mos_email_review_notes (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    TEXT        NOT NULL REFERENCES "Tenant"(id) ON DELETE CASCADE,
  campaign_id  TEXT        NOT NULL,              -- email/campaigns/{id}/
  slot         TEXT,                              -- optional section slot the note is about
  author       TEXT        NOT NULL,              -- SELF-DECLARED (see warning above)
  body         TEXT        NOT NULL,
  source       TEXT        NOT NULL DEFAULT 'link'  -- 'link' = token-gated public; 'console' = authenticated
                           CHECK (source IN ('link', 'console')),
  -- Set when the agent has acted on the note (or a human waved it off), so a
  -- session can ask for "what's still open" rather than re-reading history.
  resolved_at  TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The read the review room and the MCP tool both make: a campaign's notes,
-- oldest first.
CREATE INDEX idx_mos_email_review_notes_campaign
  ON mos_email_review_notes (tenant_id, campaign_id, created_at);

-- "What's still open across the whole calendar" — the planning-session read.
CREATE INDEX idx_mos_email_review_notes_open
  ON mos_email_review_notes (tenant_id, created_at)
  WHERE resolved_at IS NULL;

ALTER TABLE mos_email_review_notes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON mos_email_review_notes FROM authenticated, anon;

CREATE TRIGGER trg_mos_email_review_notes_updated
  BEFORE UPDATE ON mos_email_review_notes
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
`,
  },
  {
    name: "009_pack_social.sql",
    sql: `-- =============================================================================
-- 009 — pack_social: the social pack's own schema (spec 26 §3, D2/D6)
-- =============================================================================
-- The first PACK-OWNED schema. Everything before this put pack state in
-- \`public\` behind an \`mos_\` prefix; spec 25 §7 / 26 §3 replace that with a
-- namespaced schema per pack:
--
--   * clean ownership      — one schema is the pack's whole DB footprint
--   * trivial teardown     — disabling the pack is DROP SCHEMA, not a hunt
--   * collision-free       — a third-party pack cannot squat an \`mos_\` name
--
-- The social pack is FIRST-PARTY, so it may run this at enablement (spec 25
-- D4). It is nevertheless written as though it were third-party — no
-- references into another pack's tables, no assumptions about \`public\`
-- beyond the platform contracts — because that boundary is the thing that
-- makes a third-party ecosystem possible later. The migration runner keys off
-- the \`mos_skill_enablements\` row (tenant_id, pack_id, version).
--
-- WHAT LIVES HERE vs. WHAT DOES NOT (spec 26 §3, D2):
--   pack_social.posts  — PACK-PRIVATE state: platform ids, permalinks, the
--                        approval fingerprint, the bound canvas revision.
--                        Nobody outside the pack reads these.
--   public.mos_calendar_items — the SHARED view. Every channel writes it
--                        through upsertCalendarItem and the console reads it
--                        treating \`channel\`/\`status\` as opaque. Do NOT
--                        overload the calendar with pack state (D2).
--
-- Doctrine (spec 22 D1): files are truth, the DB is a rebuildable index. Every
-- column here is derived from social/posts/{id}/post.md and can be rebuilt by
-- re-reading the artifacts. Losing this table loses speed, never content.
--
-- Governance mirrors 003/004/007/008: RLS on, authenticated + anon revoked,
-- the app writes as owner through the pooled connection. Tenant isolation is
-- tenant_id + RLS, never a schema per tenant (spec 26 §3).
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS pack_social;

-- The pack's index over social/posts/{id}/post.md.
CREATE TABLE IF NOT EXISTS pack_social.posts (
  tenant_id      TEXT        NOT NULL REFERENCES "Tenant"(id) ON DELETE CASCADE,
  id             TEXT        NOT NULL,              -- social/posts/{id}/
  channel        TEXT        NOT NULL,              -- 'instagram' | 'threads' | …  (pack-owned, opaque to platform)
  calendar_month TEXT        NOT NULL,              -- YYYY-MM, or 'unscheduled'
  status         TEXT        NOT NULL,              -- the pack's lifecycle (spec 24 §1)
  scheduled_at   TIMESTAMPTZ,
  target_link    TEXT,
  copy           TEXT,

  -- Bound Design Surface (spec 23). \`surface_revn\` is the canvas revision the
  -- artifact last recorded: a canvas edit bumps it WITHOUT changing the
  -- file/page ids, which is precisely the drift the publish consent check
  -- exists to catch. Kept here so a surface can be spotted as edited without
  -- re-reading every artifact.
  surface_file_id TEXT,
  surface_page_id TEXT,
  surface_revn    INTEGER,

  -- Approve-at-schedule consent (spec 24 D2). The hash is a FINGERPRINT of the
  -- approved publish material, not an authorisation by itself — the
  -- authorisation is the Slack-actor row in public.mos_action_audit. Stored so
  -- a surface can show "approved, consent intact" without recomputing.
  approval_hash   TEXT,
  approval_at     TIMESTAMPTZ,

  -- Platform write-back after a successful publish.
  platform_id     TEXT,
  platform_permalink TEXT,
  published_at    TIMESTAMPTZ,
  failure         TEXT,

  -- Where truth lives. Explicit so an operator reading a row can always find
  -- the file that produced it.
  repo_path      TEXT        NOT NULL,

  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

  PRIMARY KEY (tenant_id, id)
);

-- The month read behind the calendar and the review month-sheet.
CREATE INDEX IF NOT EXISTS idx_pack_social_posts_month
  ON pack_social.posts (tenant_id, calendar_month, scheduled_at);

-- The cron's due-work read: what is scheduled and ready to go out.
CREATE INDEX IF NOT EXISTS idx_pack_social_posts_scheduled
  ON pack_social.posts (tenant_id, scheduled_at)
  WHERE status = 'scheduled';

ALTER TABLE pack_social.posts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON pack_social.posts FROM authenticated, anon;
REVOKE ALL ON SCHEMA pack_social FROM authenticated, anon;

-- update_updated_at() is defined by the init migration in public.
DROP TRIGGER IF EXISTS trg_pack_social_posts_updated ON pack_social.posts;
CREATE TRIGGER trg_pack_social_posts_updated
  BEFORE UPDATE ON pack_social.posts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
`,
  },
  {
    name: "010_pack_social_group_key.sql",
    sql: `-- =============================================================================
-- 010 — pack_social.posts.group_key (spec 26 D3: the review unit is a GROUP)
-- =============================================================================
-- One creative idea usually ships as several posts — an Instagram square, a
-- story, a Threads variant. Reviewed apart, a brand's register drifts between
-- platforms and nobody sees it; reviewed together, that drift is the first
-- thing you notice. So the review room's unit is the post GROUP.
--
-- D3 resolves as a CONVENTION rather than a group artifact: variants share a
-- \`groupId\` in their post.md front matter, and a post without one is its own
-- group of one (group_key falls back to the post id). No second artifact type
-- to drift from the posts it references, and this column is exactly the key a
-- first-class group artifact would later be built on.
--
-- Derived from the artifact like every other column here (spec 22 D1), so it
-- is rebuildable by re-reading posts. Backfilled to the post id, which is the
-- correct group-of-one value for every row written before this migration.
-- =============================================================================

ALTER TABLE pack_social.posts
  ADD COLUMN IF NOT EXISTS group_key TEXT;

-- Every pre-existing row is a group of one.
UPDATE pack_social.posts SET group_key = id WHERE group_key IS NULL;

ALTER TABLE pack_social.posts
  ALTER COLUMN group_key SET NOT NULL;

-- The review room's read: "every variant of this group, for this tenant".
CREATE INDEX IF NOT EXISTS idx_pack_social_posts_group
  ON pack_social.posts (tenant_id, group_key);
`,
  },
  {
    name: "011_review_notes.sql",
    sql: `-- =============================================================================
-- 011 — mos_review_notes: review notes, generalised across packs (spec 26 D1)
-- =============================================================================
-- 008 shipped \`mos_email_review_notes\`, keyed on \`campaign_id\`. Social needs
-- the same thing keyed on a post group. D1: GENERALISE rather than clone —
-- "two clones is where a third becomes inevitable", and the shape is already
-- channel-neutral apart from the column name.
--
-- ADDITIVE ON PURPOSE. This creates the generalised table and leaves
-- mos_email_review_notes untouched and serving. The email review loop was
-- proven end to end days ago; migrating it in the same stroke as introducing
-- social's notes would put a working loop at risk for no schedule gain. Social
-- writes here from day one; email moves over as its own change, once this
-- table has been exercised. Until then both exist, which is the point of doing
-- it in two steps.
--
-- The addressing is (pack_id, item_id): the pack that owns the thing being
-- discussed, and its id within that pack. For social the item is a post GROUP
-- key (spec 26 D3) — the group is the review unit, so it is the discussion
-- unit. For email it will be the campaign id.
--
-- IDENTITY WARNING (unchanged from 008, and it must never soften):
--   Notes arrive through a TOKEN-GATED PUBLIC surface. A valid token proves
--   possession of a link, NOT identity. \`author\` is free text the reviewer
--   typed. It is a courtesy label for a conversation — never an approval, an
--   authorisation, or an audit record. Approval keeps its own path: Slack, a
--   real user id, mos_action_audit. \`source\` exists to keep that distinction
--   legible forever: a future console-authenticated lane can write 'console'
--   and be trusted more without silently upgrading every 'link' row already
--   stored.
--
-- Doctrine note: notes are the deliberate EXCEPTION to files-are-truth. They
-- are conversation ABOUT an artifact, not the artifact, so they are honestly
-- DB-native. Losing them loses discussion, never content.
--
-- Governance mirrors 003/004/007/008: RLS on, authenticated + anon revoked,
-- the app writes as owner through the pooled connection.
-- =============================================================================

CREATE TABLE IF NOT EXISTS mos_review_notes (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    TEXT        NOT NULL REFERENCES "Tenant"(id) ON DELETE CASCADE,
  pack_id      TEXT        NOT NULL,              -- 'social-media' | 'email-campaign' | …
  item_id      TEXT        NOT NULL,              -- post GROUP key | campaign id
  slot         TEXT,                              -- optional sub-target (a variant, a section)
  author       TEXT        NOT NULL,              -- SELF-DECLARED (see warning above)
  body         TEXT        NOT NULL,
  source       TEXT        NOT NULL DEFAULT 'link'
                           CHECK (source IN ('link', 'console')),
  resolved_at  TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The read the review room and the MCP tool both make: one item's thread,
-- oldest first.
CREATE INDEX IF NOT EXISTS idx_mos_review_notes_item
  ON mos_review_notes (tenant_id, pack_id, item_id, created_at);

-- "What's still open" — the planning-session read, across a whole pack.
CREATE INDEX IF NOT EXISTS idx_mos_review_notes_open
  ON mos_review_notes (tenant_id, pack_id, created_at)
  WHERE resolved_at IS NULL;

ALTER TABLE mos_review_notes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON mos_review_notes FROM authenticated, anon;

DROP TRIGGER IF EXISTS trg_mos_review_notes_updated ON mos_review_notes;
CREATE TRIGGER trg_mos_review_notes_updated
  BEFORE UPDATE ON mos_review_notes
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
`,
  },
];
